spring.application.name=JMSProjPUB-SUB-03-PublisherApp
# ActiveMQ Broker URL
spring.activemq.broker-url=tcp://localhost:61616

# ActiveMQ Credentials
spring.activemq.user=admin
spring.activemq.password=admin

# Enable Pub-Sub Domain (Topic)
spring.jms.pub-sub-domain=true

## Connection Pool Settings (Optional)
#spring.activemq.pool.enabled=true
#spring.activemq.pool.max-connections=10

# Application Port
server.port=8085